app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('empresas/', include('empresas.urls')), #Agregando las rutas del arichivo url de empresas
]

app/empresas/urls.py
from django.urls import path

from . import views


# Estas rutas se deben incluir en el archivo url del proyecto, ver url de la carpeta app,
# si las rutas no se incluyen, no se puede hacer a ellas.

app_name = 'empresas'

urlpatterns = [
    # Url para las rutas. Cuando se usan clases genericas Detail, Update, y Delete.
    # La url debe ir la primary key como parametro ejemplo "<int:pk>, ver rutas"
    path('', views.EmpresaListView.as_view(), name='list'),
    
    # El path recibe 2 o 3 parametros, segun como quieras usarlo. El primer parametro es
    # la ruta, es decir la direccion. El segundo parametro es la
    # vistas (Las funciones|acciones que se deben hacer) dicha ruta. Tercer y ultimo
    # parametro es la etiqueta (nombre del path) esta etiqueta se usa en los html y vistas
    # para redireccionar
    
    # El views hace referencia al archivo views del proyecto (empresas)
    # con esto puedes acceder a las clases genericas. Despues, se debe
    # especifiar que se usara como vista, segundo parametro.
    path('detail/<int:pk>/', views.EmpresaDetail.as_view(), name='detail'),
    
    path('create/', views.EmpresaCreateView.as_view(), name='create'),
    
    path('edit/<int:pk>/', views.EmpresaUpdateView.as_view(), name='update'),
    
    path('delete/<int:pk>/', views.EmpresaDeleteView.as_view(), name='delete'),
    
]

app/empresas/models.py
from django.db import models

# Create your models here.


class Empresa(models.Model):
    nombre = models.CharField(max_length=50)
    razon_social = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    rfc = models.CharField(max_length=50)
    telefono_oficial = models.CharField(max_length=50)
    telefono_contacto = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class Business(models.Model):
    nombre = models.CharField(max_length=50)
    razon_social = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    rfc = models.CharField(max_length=50)
    telefono_oficial = models.CharField(max_length=50)
    telefono_contacto = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

app/empresas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy


# importar la clase generica (Herencia)
from django.views import generic

# Importando el modelo Empresa
# from .models import Empresa
from .models import Business
# Create your views here.



# Esta clase ayuda a paginar todo los datos de la base de datos
class EmpresaListView(generic.ListView):
    model = Business #Referencia al modelo que se va usar.
    context_object_name = 'business_list' #Variabel que hace referencia en el html.
    template_name = "empresas/list.html" #Referencia al html, se mostrar los resultados
    
# Clase generica. Obtiene un objecto por id, checar el archivo urls.py de empresas.
# Esta clase por default hace que "context_object_name" tome el nombre del modelo. 
# En este caso es business, se puede cambiar si lo deseas, solo tienes que especificar como esta arriba
class EmpresaDetail(generic.DetailView):
    model = Business
    template_name='empresas/detail.html'   

# Clase generica. Crea un objeto sin necesidad de un form, checar el archivo urls.py de empresas    
class EmpresaCreateView(generic.CreateView):
    model = Business
    template_name = "empresas/create.html"
    
    # Lista todos los campos que pertenecen al modelo especificado en model
    fields = [
        'nombre',
        'razon_social',
        'direccion',
        'rfc',
        'telefono_oficial',
        'telefono_contacto'
    ]
    success_url = reverse_lazy('empresas:list')#redirecciona a la URL especificada. obtiene la URL correspondiente al nombre especificado como argumento.

# Clase generica. Obtiene un objecto por id, checar el archivo urls.py de empresas.
# El metodo get_context_data() obtiene el context; contexto(data) y los muestra en los campos
class EmpresaUpdateView(generic.UpdateView):
    model = Business
    template_name = "empresas/create.html"
    fields = [
        'nombre',
        'razon_social',
        'direccion',
        'rfc',
        'telefono_oficial',
        'telefono_contacto'
    ]
    success_url = reverse_lazy('empresas:list')
    
    def get_context_data(self, **kwargs):
        context = super(EmpresaUpdateView, self).get_context_data(**kwargs)
        context['update'] = True
        return context

# Clase generica. Obtiene un objecto por id y lo elimina, checar el archivo urls.py de empresas.
class EmpresaDeleteView(generic.DeleteView):
    model = Business
    template_name = "empresas/delete.html"
    success_url = reverse_lazy('empresas:list')

app/empresas/templates/empresas/create.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% if update %}
    <title>Actualizar Empresa</title>
    {% else %}
    <title>Create Empresa</title>
    {% endif %}
</head>

<body>
    {% if update %}
    <h1>Actualizar Empresas</h1>
    {% else %}
    <h1>Create Empresa</h1>
    {% endif %}


    <form method="post">
        {% csrf_token %} {{ form.as_p }}

        <div class="float-left">
            <a href="{% url 'empresas:list' %}" class="btn btn-danger">Cancelar</a>
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </form>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>

</html>

app/empresas/templates/empresas/delete.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eliminar Empresa</title>
</head>

<body>
    <h1>Eliminar Empresa</h1>
    <form method="POST">
        {% csrf_token %} {% if business %}
        <center>
            <div style="width: max-content; margin:50px">
                <div class="card text-center">
                    <div class="card-header">
                        <h3>{{business.nombre}}</h3>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ business.razon_social }}</h5>
                        <h5 class="card-title">{{ business.direccion }}</h5>
                        <h5 class="card-title">{{ business.rfc }}</h5>
                        <h5 class="card-title">{{ business.telefono_oficial }}</h5>
                        <h5 class="card-title">{{ business.telefono_contacto }}</h5>
                        <div class="float">
                            <p class="delete-msg">Eliminar la empresa <b>"{{ business.nombre }}"</b>?</p>
                            <div class="float-center">
                                <a href="{% url 'empresas:list' %}" class="btn btn-danger">Cancelar</a>
                                <button class="btn btn-primary" type="submit">Si</button>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        Agavesoft
                    </div>
                </div>
            </div>
        </center>
        {% else %}
        <p>No empreas are available.</p>
        {% endif %}
    </form>
</body>

</html>

app/empresas/templates/empresas/detail.html
<html lang="en">

<head>

    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Empresa Detalle</title>
</head>

<body>

    {% if business %}
    <center>
        <div style="width: max-content; margin:50px">
            <div class="card text-center">
                <div class="card-header">
                    <h3>{{business.nombre}}</h3>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ business.razon_social }}</h5>
                    <h5 class="card-title">{{ business.direccion }}</h5>
                    <h5 class="card-title">{{ business.rfc }}</h5>
                    <h5 class="card-title">{{ business.telefono_oficial }}</h5>
                    <h5 class="card-title">{{ business.telefono_contacto }}</h5>
                    <div class="float">
                        <a href="{% url 'empresas:list' %}" class="btn btn-secondary">Back</a>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Agavesoft
                </div>
            </div>
        </div>
    </center>

    {% else %}
    <p>No empresa are available.</p>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

app/empresas/templates/empresas/list.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lista empresa</title>
</head>

<body>
    <h1>Lista empresa</h1>
    <div class="float-left">
        <a class="btn btn-primary" href="{% url 'empresas:create' %}">Crear Empresa</a>
    </div>
    {% if business_list %}
    <div class="table-responsive-md" style="width: 50%;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nombre de la empresa</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for business in business_list %}
                <tr>
                    <td>
                        <a href="{% url 'empresas:detail' business.id %}">{{ business.nombre }}</a>
                    </td>
                    <td>
                        <a class="btn btn-info" href="{% url 'empresas:update' business.id %}">editar</a>
                        <a class="btn btn-danger" href="{% url 'empresas:delete' business.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>No empresa are available.</p>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>